### ISSUE TITLE
Problem loading large xmdf/sww files

### ISSUE THREAD

**Issue by saberraz** [lutraconsulting/qgis-crayfish-plugin#100]
I have tried to open the result from TUFLOW with .xmdf file(50 GB), but I get some error like I have attached and all of the messages in python error I have show it at below, I don't know it too big file size or not, because for the small file size I can open it:

An error has occured while executing Python code:

Traceback (most recent call last):
  File "C:/Users/USER2/.qgis2/python/plugins\crayfish\crayfish_plugin.py", line 234, in addCrayfishLayer
    self.loadDatFile(inFileName)
  File "C:/Users/USER2/.qgis2/python/plugins\crayfish\crayfish_plugin.py", line 316, in loadDatFile
    parentLayer.mesh.load_data( inFileName )
  File "C:/Users/USER2/.qgis2/python/plugins\crayfish\crayfish.py", line 159, in load_data
    if not self.lib.CF_Mesh_loadDataSet(self.handle, path):
WindowsError: [Error -529697949] Windows Error 0xE06D7363

Python version:
2.7.5 (default, May 15 2013, 22:44:16) [MSC v.1500 64 bit (AMD64)]

QGIS version:
2.8.1-Wien Wien, exported

**Comment by wonder-sk** [comment]
Looks like an exception was thrown in c++ code - according to this:
https://support.microsoft.com/en-us/kb/185294

Does it work on linux?

**Comment by wonder-sk** [comment]
Crayfish currently loads the whole content of the file into the memory, so loading a file this big may have run into out-of-memory situation.

**Comment by saberraz** [comment]
Large sww files cause an error in Crayfish (11-24 GB)
When trying to open them in crayfish, the attached error message appears:
![large_sww_file](https://cloud.githubusercontent.com/assets/2649047/9080238/cb2141de-3b49-11e5-8c8f-a69305bf9003.jpg)

**Comment by saberraz** [comment]
More error reported by users for handling large XMDF:
Traceback (most recent call last):
  File "C:/Users/gaffney.WMA/.qgis2/python/plugins\crayfish\plugin.py", line 249, in addCrayfishLayer self.loadDatFile(inFileName)
  File "C:/Users/gaffney.WMA/.qgis2/python/plugins\crayfish\plugin.py", line 352, in loadDatFile parentLayer.mesh.load_data( inFileName )
  File "C:/Users/gaffney.WMA/.qgis2/python/plugins\crayfish\core.py", line 202, in load_data if not self.lib.CF_Mesh_loadDataSet(self.handle, path): WindowsError: [Error -529697949] Windows Error 0xE06D7363

**Comment by PeterPetrik** [comment]
https://github.com/lutraconsulting/MDAL/issues/13

**Comment by PeterPetrik** [comment]
From Crayfish 3.x release and QGIS 3.4 release, the rendering and styling is implemented in QGIS Core. The data reading and support is implemented in [MDAL](https://github.com/lutraconsulting/MDAL/issues).
Please reopen the ticket in QGIS bug tracker for rendering issues or MDAL for format support issues. 
Thanks.
