### ISSUE TITLE
Crayfish 2.1 installation problem in QGIS 2.6

### ISSUE THREAD

**Issue by saberraz** [lutraconsulting/qgis-crayfish-plugin#104]
![image006](https://cloud.githubusercontent.com/assets/2649047/7629971/440e8172-fa29-11e4-95a1-e9c507e14452.png)

**Comment by saberraz** [comment]
This happened when updating 2.0 to 2.1 on QGIS 2.6 when 2.8.1 was running in the background.

 

Can reproduce.

 

Couldn't load plugin crayfish due an error when calling its initGui() method

 

 

Traceback (most recent call last):

  File "C:/PROGRA~1/QGISBR~1/apps/qgis/./python\qgis\utils.py", line 217, in startPlugin

    plugins[packageName].initGui()

  File "C:/Users/pete/.qgis2/python/plugins\crayfish\crayfish_plugin.py", line 73, in initGui

    if not crayfish_install_helper.ensure_library_installed():

  File "C:/Users/pete/.qgis2/python/plugins\crayfish\crayfish_install_helper.py", line 72, in ensure_library_installed

    extractBinPackageAfterRestart()

  File "C:/Users/pete/.qgis2/python/plugins\crayfish\crayfish_install_helper.py", line 199, in extractBinPackageAfterRestart

    z.extractall(destFolder)

  File "C:\PROGRA~1\QGISBR~1\apps\Python27\lib\zipfile.py", line 1036, in extractall

    self.extract(zipinfo, path, pwd)

  File "C:\PROGRA~1\QGISBR~1\apps\Python27\lib\zipfile.py", line 1024, in extract

    return self._extract_member(member, path, pwd)

  File "C:\PROGRA~1\QGISBR~1\apps\Python27\lib\zipfile.py", line 1079, in _extract_member

    file(targetpath, "wb") as target:

IOError: [Errno 13] Permission denied: 'C:\\Users\\pete\\.qgis2\\python\\plugins\\crayfish\\crayfish.dll'

 

 

Python version:

2.7.5 (default, May 15 2013, 22:44:16) [MSC v.1500 64 bit (AMD64)]

 

 

QGIS version:

2.6.0-Brighton Brighton, exported

 

Python path: ['C:/PROGRA~1/QGISBR~1/apps/qgis/./python', u'C:/Users/pete/.qgis2/python', u'C:/Users/pete/.qgis2/python/plugins', 'C:/PROGRA~1/QGISBR~1/apps/qgis/./python/plugins', 'C:\\PROGRA~1\\QGISBR~1\\apps\\Python27\\lib\\site-packages\\matplotlib-1.3.1-py2.7-win-amd64.egg', 'C:\\PROGRA~1\\QGISBR~1\\apps\\Python27\\lib\\site-packages\\nose-1.3.3-py2.7.egg', 'C:\\PROGRA~1\\QGISBR~1\\apps\\Python27\\lib\\site-packages\\tornado-4.0.1-py2.7-win-amd64.egg', 'C:\\PROGRA~1\\QGISBR~1\\apps\\Python27\\lib\\site-packages\\backports.ssl_match_hostname-3.4.0.2-py2.7.egg', 'C:\\PROGRA~1\\QGISBR~1\\apps\\Python27\\lib\\site-packages\\certifi-14.05.14-py2.7.egg', 'C:\\PROGRA~1\\QGISBR~1\\apps\\Python27\\lib\\site-packages\\setuptools-14.0-py2.7.egg', 'C:\\Users\\pete\\.eclipse\\org.eclipse.platform_3.7.0_1709980481\\plugins\\org.python.pydev.debug_2.3.0.2011121518\\pysrc', 'C:\\Users\\pete\\Documents\\Projects\\Lutra\\qgis\\lutraTools', 'C:\\Users\\pete\\Documents\\Projects\\Lutra\\Python Course\\Briefcased Items\\Python\\Course Files\\Python Day 2\\Ex 3\\Completed Scripts', 'C:\\PROGRA~1\\QGISBR~1\\bin\\python27.zip', 'C:\\PROGRA~1\\QGISBR~1\\apps\\Python27\\DLLs', 'C:\\PROGRA~1\\QGISBR~1\\apps\\Python27\\lib', 'C:\\PROGRA~1\\QGISBR~1\\apps\\Python27\\lib\\plat-win', 'C:\\PROGRA~1\\QGISBR~1\\apps\\Python27\\lib\\lib-tk', 'C:\\PROGRA~1\\QGISBR~1\\bin', 'C:\\PROGRA~1\\QGISBR~1\\apps\\Python27', 'C:\\PROGRA~1\\QGISBR~1\\apps\\Python27\\lib\\site-packages', 'C:\\PROGRA~1\\QGISBR~1\\apps\\Python27\\lib\\site-packages\\PIL', 'C:\\PROGRA~1\\QGISBR~1\\apps\\Python27\\lib\\site-packages\\jinja2-2.7.2-py2.7.egg', 'C:\\PROGRA~1\\QGISBR~1\\apps\\Python27\\lib\\site-packages\\markupsafe-0.23-py2.7-win-amd64.egg', 'C:\\PROGRA~1\\QGISBR~1\\apps\\Python27\\lib\\site-packages\\pytz-2012j-py2.7.egg', 'C:\\PROGRA~1\\QGISBR~1\\apps\\Python27\\lib\\site-packages\\win32', 'C:\\PROGRA~1\\QGISBR~1\\apps\\Python27\\lib\\site-packages\\win32\\lib', 'C:\\PROGRA~1\\QGISBR~1\\apps\\Python27\\lib\\site-packages\\Pythonwin', 'C:\\PROGRA~1\\QGISBR~1\\apps\\Python27\\lib\\site-packages\\Shapely-1.2.18-py2.7-win-amd64.egg', 'C:\\PROGRA~1\\QGISBR~1\\apps\\Python27\\lib\\site-packages\\six-1.3.0-py2.7.egg', 'C:\\PROGRA~1\\QGISBR~1\\apps\\Python27\\lib\\site-packages\\wx-2.8-msw-unicode', 'C:\\PROGRA~1\\QGISBR~1\\apps\\Python27\\lib\\site-packages\\xlrd-0.9.2-py2.7.egg', 'C:\\PROGRA~1\\QGISBR~1\\apps\\Python27\\lib\\site-packages\\xlwt-0.7.5-py2.7.egg', 'C:\\Users\\pete\\.qgis2\\python\\plugins\\agrii-zoning-plugin/', 'C:\\Users\\pete\\.qgis2\\python\\plugins\\agrii-zoning-plugin/ui', 'C:\\Users\\pete\\.qgis2\\python\\plugins\\agrii-zoning-plugin/dialog', 'C:\\Users\\pete\\.qgis2\\python\\plugins\\agrii-zoning-plugin/task', 
path, "wb") as target:

IOError: [Errno 13] Permission denied: 'C:\\Users\\pete\\.qgis2\\python\\plugins\\crayfish\\crayfish.dll'

 

 

Python version:

2.7.5 (default, May 15 2013, 22:44:16) [MSC v.1500 64 bit (AMD64)]

 

 

QGIS version:

2.6.0-Brighton Brighton, exported

 

Python path: ['C:/PROGRA~1/QGISBR~1/apps/qgis/./python', u'C:/Users/pete/.qgis2/python', u'C:/Users/pete/.qgis2/python/plugins', 'C:/PROGRA~1/QGISBR~1/apps/qgis/./python/plugins', 'C:\\PROGRA~1\\QGISBR~1\\apps\\Python27\\lib\\site-packages\\matplotlib-1.3.1-py2.7-win-amd64.egg', 'C:\\PROGRA~1\\QGISBR~1\\apps\\Python27\\lib\\site-packages\\nose-1.3.3-py2.7.egg', 'C:\\PROGRA~1\\QGISBR~1\\apps\\Python27\\lib\\site-packages\\tornado-4.0.1-py2.7-win-amd64.egg', 'C:\\PROGRA~1\\QGISBR~1\\apps\\Python27\\lib\\site-packages\\backports.ssl_match_hostname-3.4.0.2-py2.7.egg', 'C:\\PROGRA~1\\QGISBR~1\\apps\\Python27\\lib\\site-packages\\certifi-14.05.14-py2.7.egg', 'C:\\PROGRA~1\\QGISBR~1\\apps\\Python27\\lib\\site-packages\\setuptools-14.0-py2.7.egg', 'C:\\Users\\pete\\.eclipse\\org.eclipse.platform_3.7.0_1709980481\\plugins\\org.python.pydev.debug_2.3.0.2011121518\\pysrc', 'C:\\Users\\pete\\Documents\\Projects\\Lutra\\qgis\\lutraTools', 'C:\\Users\\pete\\Documents\\Projects\\Lutra\\Python Course\\Briefcased Items\\Python\\Course Files\\Python Day 2\\Ex 3\\Completed Scripts', 'C:\\PROGRA~1\\QGISBR~1\\bin\\python27.zip', 'C:\\PROGRA~1\\QGISBR~1\\apps\\Python27\\DLLs', 'C:\\PROGRA~1\\QGISBR~1\\apps\\Python27\\lib', 'C:\\PROGRA~1\\QGISBR~1\\apps\\Python27\\lib\\plat-win', 'C:\\PROGRA~1\\QGISBR~1\\apps\\Python27\\lib\\lib-tk', 'C:\\PROGRA~1\\QGISBR~1\\bin', 'C:\\PROGRA~1\\QGISBR~1\\apps\\Python27', 'C:\\PROGRA~1\\QGISBR~1\\apps\\Python27\\lib\\site-packages', 'C:\\PROGRA~1\\QGISBR~1\\apps\\Python27\\lib\\site-packages\\PIL', 'C:\\PROGRA~1\\QGISBR~1\\apps\\Python27\\lib\\site-packages\\jinja2-2.7.2-py2.7.egg', 'C:\\PROGRA~1\\QGISBR.....

**Comment by saberraz** [comment]
It works fine with fresh installation of Crayfish 2.1. If it fails with update, consider removing 2.0 from .qgis2\python\plugins and install it from fresh.

**Comment by saberraz** [comment]
This happens with 32bit version of QGIS 2.6:

Couldn't load plugin crayfish due an error when calling its initGui() method


Traceback (most recent call last):
  File "C:/PROGRA~2/QGISBR~1/apps/qgis/./python\qgis\utils.py", line 217, in startPlugin
    plugins[packageName].initGui()
  File "C:/Users/saber/.qgis2/python/plugins\crayfish\crayfish_plugin.py", line 73, in initGui
    if not crayfish_install_helper.ensure_library_installed():
  File "C:/Users/saber/.qgis2/python/plugins\crayfish\crayfish_install_helper.py", line 131, in ensure_library_installed
    import crayfish
  File "C:/PROGRA~2/QGISBR~1/apps/qgis/./python\qgis\utils.py", line 460, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/saber/.qgis2/python/plugins\crayfish\crayfish.py", line 34, in 
    lib=ctypes.cdll.LoadLibrary(os.path.join(this_dir, libname))
  File "C:\PROGRA~2\QGISBR~1\apps\Python27\lib\ctypes\__init__.py", line 443, in LoadLibrary
    return self._dlltype(name)
  File "C:\PROGRA~2\QGISBR~1\apps\Python27\lib\ctypes\__init__.py", line 365, in __init__
    self._handle = _dlopen(self._name, mode)
WindowsError: [Error 127] The specified procedure could not be found
