### ISSUE TITLE
Export to animation error

### ISSUE THREAD

**Issue by saberraz** [lutraconsulting/qgis-crayfish-plugin#118]
An error has occured while executing Python code:

Traceback (most recent call last):
  File "C:/Users/cdobb/.qgis2/python/plugins\crayfish\crayfish_plugin.py", line 505, in exportAnimation
    dlg = crayfish_animation_dialog.CrayfishAnimationDialog(self.iface)
  File "C:/Users/cdobb/.qgis2/python/plugins\crayfish\crayfish_animation_dialog.py", line 92, in __init__
    self.restoreDefaults()
  File "C:/Users/cdobb/.qgis2/python/plugins\crayfish\crayfish_animation_dialog.py", line 323, in restoreDefaults
    self.setTimeInCombo(self.cboEnd, s.value(k,type=float))
TypeError: unable to convert a QVariant of type 0 to a QMetaType of type 6 

Python version:
2.7.5 (default, May 15 2013, 22:44:16) [MSC v.1500 64 bit (AMD64)]

**Comment by wonder-sk** [comment]
There is a way how to fix this problem in the QGIS installation. Open Python console and copy/paste these three lines of code:
```
from PyQt4.QtCore import QSettings
QSettings().remove('crayfishViewer/animation/time_start')
QSettings().remove('crayfishViewer/animation/time_end')
```
