### ISSUE TITLE
Adding nc data crashes QGIS

### ISSUE THREAD

**Issue by saberraz** [lutraconsulting/qgis-crayfish-plugin#167]
Tried to add this dataset and crashed QGIS
[MaxTemp_1961-1990_LTA_25km.zip](https://github.com/lutraconsulting/qgis-crayfish-plugin/files/222119/MaxTemp_1961-1990_LTA_25km.zip)

**Comment by saberraz** [comment]
More info:
An error has occurred while executing Python code:


Traceback (most recent call last):
  File "C:/Users/Saber/.qgis2/python/plugins\crayfish\plugin_layer.py", line 720, in legendSymbologyItems
    dsC = self.currentContourDataSet()
  File "C:/Users/Saber/.qgis2/python/plugins\crayfish\plugin_layer.py", line 221, in currentContourDataSet
    return self.mesh.dataset(self.contour_ds_index)
  File "C:/Users/Saber/.qgis2/python/plugins\crayfish\core.py", line 167, in dataset
    return DataSet.from_handle(self.lib.CF_Mesh_dataSetAt(self.handle, index))
  File "C:/Users/Saber/.qgis2/python/plugins\crayfish\core.py", line 224, in from_handle
    return DataSet(handle)
  File "C:/Users/Saber/.qgis2/python/plugins\crayfish\core.py", line 231, in __init__
    raise ValueError(handle)
ValueError: None

**Comment by PeterPetrik** [comment]
![scr11](https://cloud.githubusercontent.com/assets/804608/15502086/1cc02510-21b2-11e6-89ee-d1aedee0159e.png)

There is no dataset with metadata "NETCDF_DIM_time", e.g. the netcdf parser is unable to find any time depending bands. Hence it cannot load it into crayfish.

**Comment by PeterPetrik** [comment]
@wonder-sk please review
