### ISSUE TITLE
Problem with xmdf

### ISSUE THREAD

**Issue by saberraz** [lutraconsulting/qgis-crayfish-plugin#171]
The following problem happens (not always...it is temperamental) when trying to add results from TUFLOW 2016:

```
Traceback (most recent call last):
			  File "C:/Users/saber/.qgis2/python/plugins\crayfish\plugin.py", line 249, in addCrayfishLayer
			    self.loadDatFile(inFileName)
			  File "C:/Users/saber/.qgis2/python/plugins\crayfish\plugin.py", line 352, in loadDatFile
			    parentLayer.mesh.load_data( inFileName )
			  File "C:/Users/saber/.qgis2/python/plugins\crayfish\core.py", line 202, in load_data
			    if not self.lib.CF_Mesh_loadDataSet(self.handle, path):
			WindowsError: exception: access violation reading 0x000000005F4CA000
```

**Comment by saberraz** [comment]
[breach_xmdf_new.zip](https://github.com/lutraconsulting/qgis-crayfish-plugin/files/229236/breach_xmdf_new.zip)
Sample data generated from the latest TUFLOW release.

**Comment by saberraz** [comment]
[breach_xmdf_old.zip](https://github.com/lutraconsulting/qgis-crayfish-plugin/files/229260/breach_xmdf_old.zip)
Same model, results generated in 2013 version of TUFLOW (no error)
