### ISSUE TITLE
Pre-compiled binaries not working in Ubuntu >= 15.10

### ISSUE THREAD

**Issue by wonder-sk** [lutraconsulting/qgis-crayfish-plugin#187]
Linux binaries are built with Ubuntu 14.04, using libproj.so.0 from libproj0 package. From Ubuntu 15.10 this has been replaced by libproj9 package with libproj.so.9 library.

The load fails with the following error:
```
OSError: libproj.so.0: cannot open shared object file: No such file or directory

Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/qgis/utils.py", line 335, in startPlugin
    plugins[packageName].initGui()
  File "/home/alexandre/.qgis2/python/plugins/crayfish/plugin.py", line 73, in initGui
    if not ensure_library_installed():
  File "/home/alexandre/.qgis2/python/plugins/crayfish/gui/install_helper.py", line 133, in ensure_library_installed
    load_library()
  File "/home/alexandre/.qgis2/python/plugins/crayfish/core.py", line 85, in load_library
    lib = ctypes.cdll.LoadLibrary(libpath)
  File "/usr/lib/python2.7/ctypes/__init__.py", line 443, in LoadLibrary
    return self._dlltype(name)
  File "/usr/lib/python2.7/ctypes/__init__.py", line 365, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libproj.so.0: cannot open shared object file: No such file or directory
```

**Comment by haubourg** [comment]
hi, confirmed here with ubuntu 16.04. any workaround?

**Comment by saberraz** [comment]
@haubourg I suggest compiling it from source:

`sudo apt-get install build-essential libqt4-dev qt4-qmake libgdal-dev libhdf5-dev libnetcdf-dev libproj-dev git`

`git clone https://github.com/lutraconsulting/qgis-crayfish-plugin.git`
```
cd qgis-crayfish-plugin
export QT_SELECT=qt4
./install.py
```

A new release will be out soon and we will ship the plugin with binaries for the latest Ubuntu.

**Comment by haubourg** [comment]
Okay, thanks. I will give it a try
