### ISSUE TITLE
Pre-compiled binaries not working on Debian >= jessie

### ISSUE THREAD

**Issue by wonder-sk** [lutraconsulting/qgis-crayfish-plugin#196]
The distribution packages come with higher version of HDF5 (libhdf5.so.8 instead of libhdf5.so.7). The error:

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/qgis/utils.py", line 315, in startPlugin
    plugins[packageName].initGui()
  File "/home/tono64/.qgis2/python/plugins/crayfish/plugin.py", line 73, in initGui
    if not ensure_library_installed():
  File "/home/tono64/.qgis2/python/plugins/crayfish/gui/install_helper.py", line 133, in ensure_library_installed
    load_library()
  File "/home/tono64/.qgis2/python/plugins/crayfish/core.py", line 85, in load_library
    lib = ctypes.cdll.LoadLibrary(libpath)
  File "/usr/lib/python2.7/ctypes/__init__.py", line 443, in LoadLibrary
    return self._dlltype(name)
  File "/usr/lib/python2.7/ctypes/__init__.py", line 365, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libhdf5.so.7: cannot open shared object file: No such file or directory

Python version: 2.7.9 (default, Mar  1 2015, 13:01:26) [GCC 4.9.2] 
QGIS version: 2.14.2-Essen Essen, exported 
```

**Comment by PeterPetrik** [comment]
not an issue now, everything is removed!
