### ISSUE TITLE
Uncaught AttributeError: 'NoneType' object has no attribute 'custom'


### ISSUE THREAD

**Issue by saberraz** [lutraconsulting/qgis-crayfish-plugin#215]
Steps to reproduce
1. Load CF layer  
2. Change contour style from Basic to Advanced 

```
Traceback (most recent call last):
  File "/home/ubuntu/.qgis2/python/plugins/crayfish/gui/dock.py", line 481, in setContourType
    self.updateColorMapAndRedraw(ds)
  File "/home/ubuntu/.qgis2/python/plugins/crayfish/gui/dock.py", line 456, in updateColorMapAndRedraw
    self.updateAdvancedPreview()
  File "/home/ubuntu/.qgis2/python/plugins/crayfish/gui/dock.py", line 486, in updateAdvancedPreview
    cm = ds.custom["c_advancedColorMap"]
AttributeError: 'NoneType' object has no attribute 'custom'

```

crayfish 2.2.90, QGIS 2.8.1-Wien on Linux 3.19.0-58-generic

**Comment by PeterPetrik** [comment]
@saberraz I am unable to replicate it. Which CF input file was used?
