### ISSUE TITLE
Problem with installation - QGIS 2.12 - Crayfish 2.3.1

### ISSUE THREAD

**Issue by saberraz** [lutraconsulting/qgis-crayfish-plugin#229]
Traceback (most recent call last):
File "C:/PROGRA~1/QGISLY~1/apps/qgis/./python\qgis\utils.py", line 315, in startPlugin
plugins[packageName].initGui()
File "C:/Users/User/.qgis2/python/plugins\crayfish\plugin.py", line 77, in initGui
if not ensure_library_installed():
File "C:/Users/User/.qgis2/python/plugins\crayfish\gui\install_helper.py", line 129, in ensure_library_installed
load_library()
File "C:/Users/User/.qgis2/python/plugins\crayfish\core.py", line 73, in load_library
lib = ctypes.cdll.LoadLibrary(libpath)
File "C:\PROGRA~1\QGISLY~1\apps\Python27\lib\ctypes__init__.py", line 443, in LoadLibrary
return self._dlltype(name)
File "C:\PROGRA~1\QGISLY~1\apps\Python27\lib\ctypes__init__.py", line 365, in **init**
self._handle = _dlopen(self._name, mode)
WindowsError: [Error 126] The specified module could not be found

**Comment by PeterPetrik** [comment]
What windows version do you use?

**Comment by saberraz** [comment]
Windows 7, 64-bit

**Comment by PeterPetrik** [comment]
there is problem with missing gdal 2.x libraries. Crayfish 2.3.x works with QGIS 2.14+. 
The installation on qgis 2.12 is fixed in crayfish 2.3.2 release, to be released today or start of next week

**Comment by saberraz** [comment]
We no longer support QGIS < 2.14
