### ISSUE TITLE
Opening project with Crayfish layer in print template crashes QGIS with minidump

### ISSUE THREAD

**Issue by saberraz** [lutraconsulting/qgis-crayfish-plugin#240]
When user tries to open a project (sometimes from previous QGIS versions) with Crayfish layer in a print composer layer, it crashes QGIS:

```
2016-12-12T10:01:50 1 Traceback (most recent call last):
File "C:/Users/USER/.qgis2/python/plugins\crayfish\plugin_layer.py", line 732, in legendSymbologyItems
dsV = self.currentVectorDataSet()
File "C:/Users/USER/.qgis2/python/plugins\crayfish\plugin_layer.py", line 237, in currentVectorDataSet
return self.mesh.dataset(self.vector_ds_index)
File "C:/Users/USER/.qgis2/python/plugins\crayfish\core.py", line 262, in dataset
return DataSet.from_handle(self.lib.CF_Mesh_dataSetAt(self.handle, index))
File "C:/Users/USER/.qgis2/python/plugins\crayfish\core.py", line 319, in from_handle
return DataSet(handle)
File "C:/Users/USER/.qgis2/python/plugins\crayfish\core.py", line 326, in __init__
raise ValueError(handle)
ValueError: None
2016-12-12T10:01:50 1 Traceback (most recent call last):
File "C:/Users/USER/.qgis2/python/plugins\crayfish\plugin_layer.py", line 732, in legendSymbologyItems
dsV = self.currentVectorDataSet()
File "C:/Users/USER/.qgis2/python/plugins\crayfish\plugin_layer.py", line 237, in currentVectorDataSet
return self.mesh.dataset(self.vector_ds_index)
File "C:/Users/USER/.qgis2/python/plugins\crayfish\core.py", line 262, in dataset
return DataSet.from_handle(self.lib.CF_Mesh_dataSetAt(self.handle, index))
File "C:/Users/USER/.qgis2/python/plugins\crayfish\core.py", line 319, in from_handle
return DataSet(handle)
File "C:/Users/USER/.qgis2/python/plugins\crayfish\core.py", line 326, in __init__
raise ValueError(handle)
ValueError: None
2016-12-12T10:01:53 1 Traceback (most recent call last):
File "C:/Users/USER/.qgis2/python/plugins\crayfish\plugin_layer.py", line 732, in legendSymbologyItems
dsV = self.currentVectorDataSet()
File "C:/Users/USER/.qgis2/python/plugins\crayfish\plugin_layer.py", line 237, in currentVectorDataSet
return self.mesh.dataset(self.vector_ds_index)
File "C:/Users/USER/.qgis2/python/plugins\crayfish\core.py", line 262, in dataset
return DataSet.from_handle(self.lib.CF_Mesh_dataSetAt(self.handle, index))
File "C:/Users/USER/.qgis2/python/plugins\crayfish\core.py", line 319, in from_handle
return DataSet(handle)
File "C:/Users/USER/.qgis2/python/plugins\crayfish\core.py", line 326, in __init__
raise ValueError(handle)
ValueError: None
2016-12-12T10:01:53 1 Traceback (most recent call last):
File "C:/Users/USER/.qgis2/python/plugins\crayfish\plugin_layer.py", line 732, in legendSymbologyItems
dsV = self.currentVectorDataSet()
File "C:/Users/USER/.qgis2/python/plugins\crayfish\plugin_layer.py", line 237, in currentVectorDataSet
return self.mesh.dataset(self.vector_ds_index)
File "C:/Users/USER/.qgis2/python/plugins\crayfish\core.py", line 262, in dataset
return DataSet.from_handle(self.lib.CF_Mesh_dataSetAt(self.handle, index))
File "C:/Users/USER/.qgis2/python/plugins\crayfish\core.py", line 319, in from_handle
return DataSet(handle)
File "C:/Users/USER/.qgis2/python/plugins\crayfish\core.py", line 326, in __init__
raise ValueError(handle)
ValueError: None
2016-12-12T10:01:53 1 Traceback (most recent call last):
File "C:/Users/USER/.qgis2/python/plugins\crayfish\plugin_layer.py", line 732, in legendSymbologyItems
dsV = self.currentVectorDataSet()
File "C:/Users/USER/.qgis2/python/plugins\crayfish\plugin_layer.py", line 237, in currentVectorDataSet
return self.mesh.dataset(self.vector_ds_index)
File "C:/Users/USER/.qgis2/python/plugins\crayfish\core.py", line 262, in dataset
return DataSet.from_handle(self.lib.CF_Mesh_dataSetAt(self.handle, index))
File "C:/Users/USER/.qgis2/python/plugins\crayfish\core.py", line 319, in from_handle
return DataSet(handle)
File "C:/Users/USER/.qgis2/python/plugins\crayfish\core.py", line 326, in __init__
raise ValueError(handle)
ValueError: None
2016-12-12T10:01:53 1 Traceback (most recent call last):
File "C:/Users/USER/.qgis2/python/plugins\crayfish\plugin_layer.py", line 732, in legendSymbologyItems
dsV = self.currentVectorDataSet()
File "C:/Users/USER/.qgis2/python/plugins\crayfish\plugin_layer.py", line 237, in currentVectorDataSet
return self.mesh.dataset(self.vector_ds_index)
File "C:/Users/USER/.qgis2/python/plugins\crayfish\core.py", line 262, in dataset
return DataSet.from_handle(self.lib.CF_Mesh_dataSetAt(self.handle, index))
File "C:/Users/USER/.qgis2/python/plugins\crayfish\core.py", line 319, in from_handle
return DataSet(handle)
File "C:/Users/USER/.qgis2/python/plugins\crayfish\core.py", line 326, in __init__
raise ValueError(handle)
ValueError: None
2016-12-12T10:01:53 1 Traceback (most recent call last):
File "C:/Users/USER/.qgis2/python/plugins\crayfish\plugin_layer.py", line 732, in legendSymbologyItems
dsV = self.currentVectorDataSet()
File "C:/Users/USER/.qgis2/python/plugins\crayfish\plugin_layer.py", line 237, in currentVectorDataSet
return self.mesh.dataset(self.vector_ds_index)
File "C:/Users/USER/.qgis2/python/plugins\crayfish\core.py", line 262, in dataset
return DataSet.from_handle(self.lib.CF_Mesh_dataSetAt(self.handle, index))
File "C:/Users/USER/.qgis2/python/plugins\crayfish\core.py", line 319, in from_handle
return DataSet(handle)
File "C:/Users/USER/.qgis2/python/plugins\crayfish\core.py", line 326, in __init__
raise ValueError(handle)
ValueError: None
2016-12-12T10:01:53 1 Traceback (most recent call last):
File "C:/Users/USER/.qgis2/python/plugins\crayfish\plugin_layer.py", line 732, in legendSymbologyItems
dsV = self.currentVectorDataSet()
File "C:/Users/USER/.qgis2/python/plugins\crayfish\plugin_layer.py", line 237, in currentVectorDataSet
return self.mesh.dataset(self.vector_ds_index)
File "C:/Users/USER/.qgis2/python/plugins\crayfish\core.py", line 262, in dataset
return DataSet.from_handle(self.lib.CF_Mesh_dataSetAt(self.handle, index))
File "C:/Users/USER/.qgis2/python/plugins\crayfish\core.py", line 319, in from_handle
return DataSet(handle)
File "C:/Users/USER/.qgis2/python/plugins\crayfish\core.py", line 326, in __init__
raise ValueError(handle)
ValueError: None
2016-12-12T10:01:53 1 Traceback (most recent call last):
File "C:/Users/USER/.qgis2/python/plugins\crayfish\plugin_layer.py", line 732, in legendSymbologyItems
dsV = self.currentVectorDataSet()
File "C:/Users/USER/.qgis2/python/plugins\crayfish\plugin_layer.py", line 237, in currentVectorDataSet
return self.mesh.dataset(self.vector_ds_index)
File "C:/Users/USER/.qgis2/python/plugins\crayfish\core.py", line 262, in dataset
return DataSet.from_handle(self.lib.CF_Mesh_dataSetAt(self.handle, index))
File "C:/Users/USER/.qgis2/python/plugins\crayfish\core.py", line 319, in from_handle
return DataSet(handle)
File "C:/Users/USER/.qgis2/python/plugins\crayfish\core.py", line 326, in __init__
raise ValueError(handle)
ValueError: None
2016-12-12T10:01:53 1 Traceback (most recent call last):
File "C:/Users/USER/.qgis2/python/plugins\crayfish\plugin_layer.py", line 732, in legendSymbologyItems
dsV = self.currentVectorDataSet()
File "C:/Users/USER/.qgis2/python/plugins\crayfish\plugin_layer.py", line 237, in currentVectorDataSet
return self.mesh.dataset(self.vector_ds_index)
File "C:/Users/USER/.qgis2/python/plugins\crayfish\core.py", line 262, in dataset
return DataSet.from_handle(self.lib.CF_Mesh_dataSetAt(self.handle, index))
File "C:/Users/USER/.qgis2/python/plugins\crayfish\core.py", line 319, in from_handle
return DataSet(handle)
File "C:/Users/USER/.qgis2/python/plugins\crayfish\core.py", line 326, in __init__
raise ValueError(handle)
ValueError: None
2016-12-12T10:01:57 1 Traceback (most recent call last):
File "C:/Users/USER/.qgis2/python/plugins\crayfish\plugin_layer.py", line 732, in legendSymbologyItems
dsV = self.currentVectorDataSet()
File "C:/Users/USER/.qgis2/python/plugins\crayfish\plugin_layer.py", line 237, in currentVectorDataSet
return self.mesh.dataset(self.vector_ds_index)
File "C:/Users/USER/.qgis2/python/plugins\crayfish\core.py", line 262, in dataset
return DataSet.from_handle(self.lib.CF_Mesh_dataSetAt(self.handle, index))
File "C:/Users/USER/.qgis2/python/plugins\crayfish\core.py", line 319, in from_handle
return DataSet(handle)
File "C:/Users/USER/.qgis2/python/plugins\crayfish\core.py", line 326, in __init__
raise ValueError(handle)
ValueError: None
2016-12-12T10:01:57 1 Traceback (most recent call last):
File "C:/Users/USER/.qgis2/python/plugins\crayfish\plugin_layer.py", line 732, in legendSymbologyItems
dsV = self.currentVectorDataSet()
File "C:/Users/USER/.qgis2/python/plugins\crayfish\plugin_layer.py", line 237, in currentVectorDataSet
return self.mesh.dataset(self.vector_ds_index)
File "C:/Users/USER/.qgis2/python/plugins\crayfish\core.py", line 262, in dataset
return DataSet.from_handle(self.lib.CF_Mesh_dataSetAt(self.handle, index))
File "C:/Users/USER/.qgis2/python/plugins\crayfish\core.py", line 319, in from_handle
return DataSet(handle)
File "C:/Users/USER/.qgis2/python/plugins\crayfish\core.py", line 326, in __init__
raise ValueError(handle)
ValueError: None
2016-12-12T10:01:57 1 Traceback (most recent call last):
File "C:/Users/USER/.qgis2/python/plugins\crayfish\plugin_layer.py", line 732, in legendSymbologyItems
dsV = self.currentVectorDataSet()
File "C:/Users/USER/.qgis2/python/plugins\crayfish\plugin_layer.py", line 237, in currentVectorDataSet
return self.mesh.dataset(self.vector_ds_index)
File "C:/Users/USER/.qgis2/python/plugins\crayfish\core.py", line 262, in dataset
return DataSet.from_handle(self.lib.CF_Mesh_dataSetAt(self.handle, index))
File "C:/Users/USER/.qgis2/python/plugins\crayfish\core.py", line 319, in from_handle
return DataSet(handle)
File "C:/Users/USER/.qgis2/python/plugins\crayfish\core.py", line 326, in __init__
raise ValueError(handle)
ValueError: None
2016-12-12T10:01:57 1 Traceback (most recent call last):
File "C:/Users/USER/.qgis2/python/plugins\crayfish\plugin_layer.py", line 732, in legendSymbologyItems
dsV = self.currentVectorDataSet()
File "C:/Users/USER/.qgis2/python/plugins\crayfish\plugin_layer.py", line 237, in currentVectorDataSet
return self.mesh.dataset(self.vector_ds_index)
File "C:/Users/USER/.qgis2/python/plugins\crayfish\core.py", line 262, in dataset
return DataSet.from_handle(self.lib.CF_Mesh_dataSetAt(self.handle, index))
File "C:/Users/USER/.qgis2/python/plugins\crayfish\core.py", line 319, in from_handle
return DataSet(handle)
File "C:/Users/USER/.qgis2/python/plugins\crayfish\core.py", line 326, in __init__
raise ValueError(handle)
ValueError: None
2016-12-12T10:02:01 1 Traceback (most recent call last):
File "C:/Users/USER/.qgis2/python/plugins\crayfish\plugin_layer.py", line 732, in legendSymbologyItems
dsV = self.currentVectorDataSet()
File "C:/Users/USER/.qgis2/python/plugins\crayfish\plugin_layer.py", line 237, in currentVectorDataSet
return self.mesh.dataset(self.vector_ds_index)
File "C:/Users/USER/.qgis2/python/plugins\crayfish\core.py", line 262, in dataset
return DataSet.from_handle(self.lib.CF_Mesh_dataSetAt(self.handle, index))
File "C:/Users/USER/.qgis2/python/plugins\crayfish\core.py", line 319, in from_handle
return DataSet(handle)
File "C:/Users/USER/.qgis2/python/plugins\crayfish\core.py", line 326, in __init__
raise ValueError(handle)
ValueError: None
2016-12-12T10:02:01 1 Traceback (most recent call last):
File "C:/Users/USER/.qgis2/python/plugins\crayfish\plugin_layer.py", line 732, in legendSymbologyItems
dsV = self.currentVectorDataSet()
File "C:/Users/USER/.qgis2/python/plugins\crayfish\plugin_layer.py", line 237, in currentVectorDataSet
return self.mesh.dataset(self.vector_ds_index)
File "C:/Users/USER/.qgis2/python/plugins\crayfish\core.py", line 262, in dataset
return DataSet.from_handle(self.lib.CF_Mesh_dataSetAt(self.handle, index))
File "C:/Users/USER/.qgis2/python/plugins\crayfish\core.py", line 319, in from_handle
return DataSet(handle)
File "C:/Users/USER/.qgis2/python/plugins\crayfish\core.py", line 326, in __init__
raise ValueError(handle)
ValueError: None
```

**Comment by PeterPetrik** [comment]
@saberraz Can you please write me exact point how to replicate issue?

**Comment by saberraz** [comment]
Not reproducible in QGIS 2.18 under linux.
