### ISSUE TITLE
Problem with opening SOL files

### ISSUE THREAD

**Issue by saberraz** [lutraconsulting/qgis-crayfish-plugin#241]
Here is the error message:

```
2016-12-12T10:04:20 1 Traceback (most recent call last):
File "C:/Users/USER/.qgis2/python/plugins\crayfish\plugin.py", line 430, in locateMeshForFailedDatFile
layerWith2dm = self.addLayer(inFileName)
File "C:/Users/USER/.qgis2/python/plugins\crayfish\plugin.py", line 473, in addLayer
layer = CrayfishPluginLayer(twoDMFileName)
File "C:/Users/USER/.qgis2/python/plugins\crayfish\plugin_layer.py", line 127, in __init__
self.loadMesh(meshFileName)
File "C:/Users/USER/.qgis2/python/plugins\crayfish\plugin_layer.py", line 159, in loadMesh
self.mesh = Mesh(meshFileName)
File "C:/Users/USER/.qgis2/python/plugins\crayfish\core.py", line 225, in __init__
handle = self.lib.CF_LoadMesh(path)
WindowsError: exception: access violation writing 0x0000000000000000

```

**Comment by saberraz** [comment]
Crayfish must read all the files, including xyz empty files.
If you save only non empty xyz files, it doesn't work and gives this error message.
