### ISSUE TITLE
Problem with opening 2dm files

### ISSUE THREAD

**Issue by saberraz** [lutraconsulting/qgis-crayfish-plugin#242]
Steps to reproduce
 1. Open QGIS
 2. Try to add a 2dm file (generated by Basement)
 3. Crash

```
Traceback (most recent call last):
  File "C:/Users/Saber/.qgis2/python/plugins\crayfish\plugin.py", line 266, in addCrayfishLayer
    if not self.loadMesh(inFileName, fileType):
  File "C:/Users/Saber/.qgis2/python/plugins\crayfish\plugin.py", line 304, in loadMesh
    if self.addLayer(data_source): # addLayer() reports errors/warnings
  File "C:/Users/Saber/.qgis2/python/plugins\crayfish\plugin.py", line 473, in addLayer
    layer = CrayfishPluginLayer(twoDMFileName)
  File "C:/Users/Saber/.qgis2/python/plugins\crayfish\plugin_layer.py", line 127, in __init__
    self.loadMesh(meshFileName)
  File "C:/Users/Saber/.qgis2/python/plugins\crayfish\plugin_layer.py", line 159, in loadMesh
    self.mesh = Mesh(meshFileName)
  File "C:/Users/Saber/.qgis2/python/plugins\crayfish\core.py", line 225, in __init__
    handle = self.lib.CF_LoadMesh(path)
WindowsError: exception: access violation writing 0x0000000000000000

```
crayfish 2.3.2, QGIS 2.14.9-Essen on Windows 7

**Comment by saberraz** [comment]
Possible duplicate of #241
