### ISSUE TITLE
Problem with nc and grb in Ubuntu 16.04

### ISSUE THREAD

**Issue by saberraz** [lutraconsulting/qgis-crayfish-plugin#263]
When I try to open a grb or nc layer in crayfish, It does not work and I get this message :

An error has occurred while executing Python code: 

ArgumentError: argument 1: : 'ascii' codec can't encode character u'\xe9' in position 13: ordinal not in range(128) 
Traceback (most recent call last):
  File "/home/simon/.qgis2/python/plugins/crayfish/plugin.py", line 266, in addCrayfishLayer
    if not self.loadMesh(inFileName, fileType):
  File "/home/simon/.qgis2/python/plugins/crayfish/plugin.py", line 305, in loadMesh
    if self.addLayer(data_source): # addLayer() reports errors/warnings
  File "/home/simon/.qgis2/python/plugins/crayfish/plugin.py", line 477, in addLayer
    layer = CrayfishPluginLayer(twoDMFileName)
  File "/home/simon/.qgis2/python/plugins/crayfish/plugin_layer.py", line 127, in __init__
    self.loadMesh(meshFileName)
  File "/home/simon/.qgis2/python/plugins/crayfish/plugin_layer.py", line 159, in loadMesh
    self.mesh = Mesh(meshFileName)
  File "/home/simon/.qgis2/python/plugins/crayfish/core.py", line 225, in __init__
    handle = self.lib.CF_LoadMesh(path)
ArgumentError: argument 1: : 'ascii' codec can't encode character u'\xe9' in position 13: ordinal not in range(128)

**Comment by PeterPetrik** [comment]
I need some dataset to replicate it

**Comment by saberraz** [comment]
I have managed to test Crayfish in 16.04

I think the issue is related to the installation as it can't find gdal20:

Couldn't load plugin crayfish due to an error when calling its initGui() method 

```
OSError: libgdal.so.20: cannot open shared object file: No such file or directory 
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/qgis/utils.py", line 342, in startPlugin
    plugins[packageName].initGui()
  File "/home/kubuntu/.qgis2/python/plugins/crayfish/plugin.py", line 77, in initGui
    if not ensure_library_installed():
  File "/home/kubuntu/.qgis2/python/plugins/crayfish/gui/install_helper.py", line 125, in ensure_library_installed
    load_library()
  File "/home/kubuntu/.qgis2/python/plugins/crayfish/core.py", line 73, in load_library
    lib = ctypes.cdll.LoadLibrary(libpath)
  File "/usr/lib/python2.7/ctypes/__init__.py", line 440, in LoadLibrary
    return self._dlltype(name)
  File "/usr/lib/python2.7/ctypes/__init__.py", line 362, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libgdal.so.20: cannot open shared object file: No such file or directory
```
