### ISSUE TITLE
grib.nc error when adding as qgis crayfish layer

### ISSUE THREAD

**Issue by cristoph15** [lutraconsulting/qgis-crayfish-plugin#270]
Sorry for a very late add (bump) is the new word. I have this file, that will not load into qgis 2.18 crayfish 2.4.0. It states " Invalid or missing data ". Any and all help is appreciated
. Test the file out. It may just be either my computer or my copy of qgis 2.18.

http://threddsbackup.ucar.edu/thredds/ncss/grib/NCEP/MRMS/Precip/MRMS_Precip_20170214_2000.grib2?var=PrecipFlag_altitude_above_msl&north=35.82&west=-104.5&east=-90.66&south=28.5&disableProjSubset=on&horizStride=1&time_start=2017-02-14T20%3A00%3A00Z&time_end=2017-02-14T20%3A58%3A00Z&timeStride=1&vertCoord=&accept=netcdf

**Comment by saberraz** [comment]
```
An error has occurred while executing Python code: 

ValueError: None 
Traceback (most recent call last):
  File "/home/saber/.qgis2/python/plugins/crayfish/plugin_layer.py", line 775, in legendSymbologyItems
    dsC = self.currentContourDataSet()
  File "/home/saber/.qgis2/python/plugins/crayfish/plugin_layer.py", line 235, in currentContourDataSet
    return self.mesh.dataset(self.contour_ds_index)
  File "/home/saber/.qgis2/python/plugins/crayfish/core.py", line 267, in dataset
    return DataSet.from_handle(self.lib.CF_Mesh_dataSetAt(self.handle, index))
  File "/home/saber/.qgis2/python/plugins/crayfish/core.py", line 324, in from_handle
    return DataSet(handle)
  File "/home/saber/.qgis2/python/plugins/crayfish/core.py", line 331, in __init__
    raise ValueError(handle)
ValueError: None
```

**Comment by saberraz** [comment]
Tested in 2.4 and 2.5:
2.4: error message
2.5: crashing QGIS

**Comment by saberraz** [comment]
Seems to be working...but it is very slow.
