### ISSUE TITLE
‘class QString’ has no member named ‘toAscii’

### ISSUE THREAD

**Issue by jamal919** [lutraconsulting/qgis-crayfish-plugin#316]
Message shown when compiling in Fedora 27. It seems that .toAscii method is depreciated.

After downloading the source code and installing necessary dependency I issued the following command - 
export QT_SELECT=qt4
./install.py

Terminal output  - 
```
$ ./install.py 
crayfish_mesh.cpp: In member function ‘bool Mesh::reprojectMesh()’:
crayfish_mesh.cpp:648:43: error: ‘class QString’ has no member named ‘toAscii’
   projPJ projSrc = pj_init_plus(mSrcProj4.toAscii().data());
                                           ^~~~~~~
crayfish_mesh.cpp:656:44: error: ‘class QString’ has no member named ‘toAscii’
   projPJ projDst = pj_init_plus(mDestProj4.toAscii().data());
                                            ^~~~~~~
make: *** [Makefile:912: crayfish_mesh.o] Error 1
Traceback (most recent call last):
  File "./install.py", line 68, in <module>
    if not os.path.exists(plugin_dir):
  File "./install.py", line 53, in make_and_install
    print("  -pkg      Create .zip package for distribution instead of installation")
  File "./install.py", line 38, in run_cmd
    
Exception: "make" command failed
```
Thanks.

**Comment by jamal919** [comment]
Update: 

I have found the problem. It is due to an anaconda installation and the qt library included in that. After deleting the anaconda installation, the compilation worked without error (with warnings).

**Comment by saberraz** [comment]
export QT_SELECT=qt4 should set it to the correct version of Qt needed by Crayfish.
