### ISSUE TITLE
Error when exporting to animation: Cannot allocate memory

### ISSUE THREAD

**Issue by saberraz** [lutraconsulting/qgis-crayfish-plugin#372]
```
An error has occurred while executing Python code: 

OSError: [Errno 12] Cannot allocate memory 
Traceback (most recent call last):
  File "/home/saber/.local/share/QGIS/QGIS3/profiles/default/python/plugins/crayfish/gui/animation_dialog.py", line 251, in onOK
    ffmpeg_res, logfile = images_to_video(img_output_tpl, output_file, fps, self.quality(), ffmpeg_bin)
  File "/home/saber/.local/share/QGIS/QGIS3/profiles/default/python/plugins/crayfish/animation.py", line 268, in images_to_video
    res = subprocess.call(cmd, stdin=subprocess.PIPE, stdout=f, stderr=f)
  File "/usr/lib/python3.6/subprocess.py", line 267, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/usr/lib/python3.6/subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.6/subprocess.py", line 1275, in _execute_child
    restore_signals, start_new_session, preexec_fn)
OSError: [Errno 12] Cannot allocate memory
```

**Comment by sgofferj** [comment]
Same here.
Ubuntu 18.04, QGIS 3.4
AMD Ryzen 7 1700X, 16GB RAM, "free" says 3.9GB free

**Comment by sgofferj** [comment]
```
OSError: [Errno 12] Cannot allocate memory 
Traceback (most recent call last):
  File "/home/sgofferj/.local/share/QGIS/QGIS3/profiles/default/python/plugins/crayfish/gui/animation_dialog.py", line 249, in onOK
    ffmpeg_res, logfile = images_to_video(img_output_tpl, output_file, fps, self.quality(), ffmpeg_bin)
  File "/home/sgofferj/.local/share/QGIS/QGIS3/profiles/default/python/plugins/crayfish/animation.py", line 245, in images_to_video
    res = subprocess.call(cmd, stdin=subprocess.PIPE, stdout=f, stderr=f)
  File "/usr/lib/python3.6/subprocess.py", line 267, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/usr/lib/python3.6/subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.6/subprocess.py", line 1275, in _execute_child
    restore_signals, start_new_session, preexec_fn)
OSError: [Errno 12] Cannot allocate memory


Python version: 3.6.7 (default, Oct 22 2018, 11:32:17) [GCC 8.2.0] 
QGIS version: 3.4.4-Madeira Madeira, f6ddc62 

Python Path:
/usr/share/qgis/python
/home/sgofferj/.local/share/QGIS/QGIS3/profiles/default/python
/home/sgofferj/.local/share/QGIS/QGIS3/profiles/default/python/plugins
/usr/share/qgis/python/plugins
/usr/lib/python36.zip
/usr/lib/python3.6
/usr/lib/python3.6/lib-dynload
/usr/local/lib/python3.6/dist-packages
/usr/lib/python3/dist-packages
/home/sgofferj/.local/share/QGIS/QGIS3/profiles/default/python
/media/serverhome/sgofferj/Documents/maps
```

**Comment by PeterPetrik** [comment]
unable to reproduce
