### ISSUE TITLE
Couldn't load plugin 'crayfish' due to an error when calling its classFactory() method

### ISSUE THREAD

**Issue by palousegeo** [lutraconsulting/qgis-crayfish-plugin#429]
I get the error message below. I've tried the current release, LTR, and nightly versions of QGIS. I also tried loading a new profile. All with the same results. I using Windows 10.

AttributeError: type object 'h5py.h5.H5PYConfig' has no attribute '__reduce_cython__' 
Traceback (most recent call last):
  File "D:/OSGeo4W64/apps/qgis/./python\qgis\utils.py", line 334, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "C:/Users/palou/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\crayfish\__init__.py", line 29, in classFactory
    from .plugin import CrayfishPlugin
  File "D:/OSGeo4W64/apps/qgis/./python\qgis\utils.py", line 744, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/palou/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\crayfish\plugin.py", line 31, in 
    from .gui.plot_widget import CrayfishPlotWidget
  File "D:/OSGeo4W64/apps/qgis/./python\qgis\utils.py", line 744, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/palou/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\crayfish\gui\plot_widget.py", line 47, in 
    from ..plot import timeseries_plot_data, cross_section_plot_data, colors, integral_plot_data
  File "D:/OSGeo4W64/apps/qgis/./python\qgis\utils.py", line 744, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/palou/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\crayfish\plot.py", line 33, in 
    from pyqtgraph.exporters import ImageExporter
  File "D:/OSGeo4W64/apps/qgis/./python\qgis\utils.py", line 744, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users\palou\AppData\Local\pca4cd\python37\lib\site-packages\pyqtgraph\exporters\__init__.py", line 7, in 
    from .HDF5Exporter import *
  File "D:/OSGeo4W64/apps/qgis/./python\qgis\utils.py", line 744, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users\palou\AppData\Local\pca4cd\python37\lib\site-packages\pyqtgraph\exporters\HDF5Exporter.py", line 8, in 
    import h5py
  File "D:/OSGeo4W64/apps/qgis/./python\qgis\utils.py", line 744, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "D:\OSGeo4W64\apps\Python37\lib\site-packages\h5py\__init__.py", line 34, in 
    from . import version
  File "D:/OSGeo4W64/apps/qgis/./python\qgis\utils.py", line 744, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "D:\OSGeo4W64\apps\Python37\lib\site-packages\h5py\version.py", line 17, in 
    from . import h5 as _h5
  File "D:/OSGeo4W64/apps/qgis/./python\qgis\utils.py", line 744, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "h5py\h5.pyx", line 41, in init h5py.h5
AttributeError: type object 'h5py.h5.H5PYConfig' has no attribute '__reduce_cython__'

Python version: 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)] 
QGIS version: 3.12.1-București București, 121cc00ff0 

Python Path:
C:/Users/palou/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\mappia_publisher
D:/OSGeo4W64/apps/qgis/./python
C:/Users/palou/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/palou/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
D:/OSGeo4W64/apps/qgis/./python/plugins
D:\OSGeo4W64\apps\Python37
D:\OSGeo4W64\apps\Python37\Scripts
D:\OSGeo4W64\bin\python37.zip
D:\OSGeo4W64\apps\Python37\DLLs
D:\OSGeo4W64\apps\Python37\lib
D:\OSGeo4W64\bin
D:\OSGeo4W64\apps\Python37\lib\site-packages
D:\OSGeo4W64\apps\Python37\lib\site-packages\win32
D:\OSGeo4W64\apps\Python37\lib\site-packages\win32\lib
D:\OSGeo4W64\apps\Python37\lib\site-packages\Pythonwin
C:/Users/palou/AppData/Roaming/QGIS/QGIS3\profiles\default/python
D:\OSGeo4W64\apps\Python37\lib\site-packages\IPython\extensions
C:\Users\palou\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\DigitizingTools\tools
C:\Users\palou\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\DigitizingTools
C:\Users\palou\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\mmqgis/forms
C:\Users\palou\AppData\Local\pca4cd\python37
C:\Users\palou\AppData\Local\pca4cd\python37\lib\site-packages
.
Thanks, Rick

**Comment by PeterPetrik** [comment]
Hi @palousegeo , can you please open Python console in QGIS and type `import h5py`
and let me know if you see the same error as above or not? thanks

**Comment by palousegeo** [comment]
Hi Peter,
I got an error, although it is not identical:
![image](https://user-images.githubusercontent.com/3526696/79253605-5787b000-7e38-11ea-8cde-14e9009e0599.png)

**Comment by PeterPetrik** [comment]
In that case, it is problem with the installation of the h5py package in the OSGeo4W, please report to the maintainers of the OSGeo4W.
