### ISSUE TITLE
usage of removed signal

### ISSUE THREAD

**Issue by PeterPetrik** [lutraconsulting/qgis-crayfish-plugin#441]
https://github.com/lutraconsulting/qgis-crayfish-plugin/blob/b869cc159dc7c5a17291befbd09fd524750be663/crayfish/gui/plot_dataset_groups_widget.py#L56

occures when panning the map with with the plot opened

**Comment by vcloarec** [comment]
In the traceback, the  issue come from `activeScalarDatasetChanged`:
```
AttributeError: 'QgsMeshLayer' object has no attribute 'activeScalarDatasetChanged' 
Traceback (most recent call last):
  File "C:/Users/dam_ar/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\crayfish\gui\plot_widget.py", line 239, in on_layer_changed
    self.btn_dataset_group.set_layer(layer)
  File "C:/Users/dam_ar/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\crayfish\gui\plot_dataset_groups_widget.py", line 119, in set_layer
    self.menu_datasets.set_layer(layer)
  File "C:/Users/dam_ar/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\crayfish\gui\plot_dataset_groups_widget.py", line 86, in set_layer
    self.populate_actions(layer)
  File "C:/Users/dam_ar/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\crayfish\gui\plot_dataset_groups_widget.py", line 56, in populate_actions
    layer.activeScalarDatasetChanged.connect(self.on_current_dataset_changed)
AttributeError: 'QgsMeshLayer' object has no attribute '`activeScalarDatasetChanged`'
```
But, with last crayfish release, this method are not called anymore because in the QGIS API, this method was replaced by `activeScalarDatasetGroupChanged`. This seems to be an issue from using old crayfish release.
