### ISSUE TITLE
Standalone Python Crayfish processing: Incorrect parameter value for CRAYFISH_INPUT_TIMESTEP

### ISSUE THREAD

**Issue by maetal** [lutraconsulting/qgis-crayfish-plugin#449]
I am trying to convert meshes to faces-polygons using a standalone python-script. I successfully added the CrayfishProcessingProvider to the progessingRegistry but I am unable to execute the algorithm.
- The QualityMesh.shp can be created without problems using the Toolbox in QGIS
- Afterwards I copied the code from the Processing history and added it to my standalone script.

Here the code snippet I am using:
```
meshfilepath='C:/Temp/Mesh.2dm'`
timestep=0
output='C:/Temp/QualityMesh.shp'

param = {'CRAYFISH_INPUT_LAYER':meshfilepath,
		 'CRAYFISH_INPUT_DATASETS':[],
		 'CRAYFISH_INPUT_TIMESTEP':timestep,
		 'OUTPUT':output}

feedback = QgsProcessingFeedback()
alg_name='crayfish:CrayfishExportMeshFaces'

res = processing.run(alg_name,param,feedback=feedback)
print(res)
```

The code crashed with the following error:
```
File "C:/OSGEO4~1/apps/qgis/./python/plugins\processing\core\Processing.py", line 137, in runAlgorithm
    raise QgsProcessingException(msg)
_core.QgsProcessingException: Unable to execute algorithm
Incorrect parameter value for CRAYFISH_INPUT_TIMESTEP
```
--> I get the same error running the code from the Processing-History it in the Python-Console in QGIS

When using the GUI-based Processing toolbox I get a Dropdown-List for "Timestep" where only one value is present: '0:00:00'.
![grafik](https://user-images.githubusercontent.com/66322465/83544476-3bca8d00-a4fe-11ea-9c7b-b9b2805ed542.png)

I have tried various parameter values for CRAYFISH_INPUT_TIMESTEP, including int and str as it is mentioned in `processing.algorithmHelp('crayfish:CrayfishExportMeshFaces')`

What is the default/correct input value for CRAYFISH_INPUT_TIMESTEP?
Thank you and best regards!

**Comment by PeterPetrik** [comment]
Timestep is `QgsMeshDatasetIndex` representing the index of group&time, you can look at the implementation around this https://github.com/lutraconsulting/qgis-crayfish-plugin/blob/5909d85d999974fc0b9a70851d6459873b4e0abb/crayfish/processing/parameters.py#L131

so you probably need `QgsMeshDatasetIndex(0, 0)` or so (for first dataset group and first timestep)

**Comment by maetal** [comment]
May I ask you to give some more details to what exactly should the CRAYFISH_INPUT_TIMESTEP value be, in the form of `timestep= {0,0}` ? I can't get the script to work with the given information above.

Thanks a lot!

**Comment by PeterPetrik** [comment]
`timestep=QgsMeshDatasetIndex(0, 0)` ?

**Comment by maetal** [comment]
Unfortunately this does not work.
Code in the QGIS python console:
```
timestep=QgsMeshDatasetIndex(0, 0)

processing.run("crayfish:CrayfishExportMeshFaces", {'CRAYFISH_INPUT_LAYER':'C:/Temp/Mesh.2dm','CRAYFISH_INPUT_DATASETS':[],'CRAYFISH_INPUT_TIMESTEP':timestep,'OUTPUT':'C:/Temp/QualityMesh.shp'})
```

Error:
```
Traceback (most recent call last):
  File "C:\OSGEO4~1\apps\Python37\lib\code.py", line 90, in runcode
    exec(code, self.locals)
  File "<input>", line 1, in <module>
  File "<string>", line 3, in <module>
  File "C:/OSGEO4~1/apps/qgis/./python/plugins\processing\tools\general.py", line 106, in run
    return Processing.runAlgorithm(algOrName, parameters, onFinish, feedback, context)
  File "C:/OSGEO4~1/apps/qgis/./python/plugins\processing\core\Processing.py", line 137, in runAlgorithm
    raise QgsProcessingException(msg)
_core.QgsProcessingException: Unable to execute algorithm
Incorrect parameter value for CRAYFISH_INPUT_TIMESTEP
```

**Comment by PeterPetrik** [comment]
Thinking about it, the timestep parameter is only in the plugin and not natively supported in QGIS core. So maybe it does not work ATM from script. 

we are planning to port the whole processing to QGIS, but we are looking for funds and time slot.

**Comment by saberraz** [comment]
@maetal could you try again with the latest Crayfish and QGIS?
