### ISSUE TITLE
Uncaught AttributeError: 'QgsMeshLayer' object has no attribute 'activeScalarDatasetChanged'


### ISSUE THREAD

**Issue by zoran2k** [lutraconsulting/qgis-crayfish-plugin#459]
Steps to reproduce
 1. First 
 2. Second 
 3. Third 

```
Traceback (most recent call last):
  File "C:/Users/user9/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\crayfish\gui\plot_widget.py", line 239, in on_layer_changed
    self.btn_dataset_group.set_layer(layer)
  File "C:/Users/user9/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\crayfish\gui\plot_dataset_groups_widget.py", line 119, in set_layer
    self.menu_datasets.set_layer(layer)
  File "C:/Users/user9/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\crayfish\gui\plot_dataset_groups_widget.py", line 86, in set_layer
    self.populate_actions(layer)
  File "C:/Users/user9/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\crayfish\gui\plot_dataset_groups_widget.py", line 56, in populate_actions
    layer.activeScalarDatasetChanged.connect(self.on_current_dataset_changed)
AttributeError: 'QgsMeshLayer' object has no attribute 'activeScalarDatasetChanged'

```
crayfish 3.2.1, QGIS 3.14.0-Pi on Windows 10

**Comment by PeterPetrik** [comment]
@zoran2k can you please update to crayfish 3.4.4 ?
