### ISSUE TITLE
Plugin not loaded when starting QGIS

### ISSUE THREAD

**Issue by saberraz** [lutraconsulting/qgis-crayfish-plugin#463]
```
Couldn't load plugin 'crayfish' due to an error when calling its classFactory() method 

ImportError: cannot import name 'QgsMeshCalculator' from 'qgis.analysis' (/usr/local/src/QGIS_master/build/output/python/qgis/analysis/__init__.py) 
Traceback (most recent call last):
  File "/usr/local/src/QGIS_master/build/output/python/qgis/utils.py", line 334, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "/home/saber/.local/share/QGIS/QGIS3/profiles/default/python/plugins/crayfish/__init__.py", line 29, in classFactory
    from .plugin import CrayfishPlugin
  File "/usr/local/src/QGIS_master/build/output/python/qgis/utils.py", line 743, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/saber/.local/share/QGIS/QGIS3/profiles/default/python/plugins/crayfish/plugin.py", line 35, in 
    from .processing import CrayfishProcessingProvider
  File "/usr/local/src/QGIS_master/build/output/python/qgis/utils.py", line 743, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/saber/.local/share/QGIS/QGIS3/profiles/default/python/plugins/crayfish/processing/__init__.py", line 36, in 
    from .calculator import MeshCalculatorAlgorithm
  File "/usr/local/src/QGIS_master/build/output/python/qgis/utils.py", line 743, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/saber/.local/share/QGIS/QGIS3/profiles/default/python/plugins/crayfish/processing/calculator.py", line 39, in 
    from qgis.analysis import QgsMeshCalculator
ImportError: cannot import name 'QgsMeshCalculator' from 'qgis.analysis' (/usr/local/src/QGIS_master/build/output/python/qgis/analysis/__init__.py)

```

**Comment by PeterPetrik** [comment]
this is only on master, right. @vcloarec moved it to core, so probably worth to fix the crayfish ...

**Comment by saberraz** [comment]
Correct. It is on QGIS master and Crayfish 3.4.4
