### ISSUE TITLE
Cannot run in Python Console: Incorrect parameter value for CRAYFISH_INPUT_DATASET

### ISSUE THREAD

**Issue by filipurbanvrv** [lutraconsulting/qgis-crayfish-plugin#470]
Cannot run any processing script in Python Console where is in parameter CRAYFISH_INPUT_DATASET or CRAYFISH_INPUT_DATASETS or CRAYFISH_INPUT_GROUP or CRAYFISH_INPUT_TIMESTEP.

```pythonscript processing.run("crayfish:Crayfish2dTimeseriesPlot", {'CRAYFISH_INPUT_LAYER':'D:/xxxxxx/mesh.nc','CRAYFISH_INPUT_DATASET':0,'CRAYFISH_INPUT_POINTS':'points.shp','OUTPUT_FILE':'TEMPORARY_OUTPUT'}) ```

```pythonscript
Traceback (most recent call last):
  File "C:\PROGRA~1\QGIS3~1.16\apps\Python37\lib\code.py", line 90, in runcode
    exec(code, self.locals)
  File "<input>", line 1, in <module>
  File "C:/PROGRA~1/QGIS3~1.16/apps/qgis/./python/plugins\processing\tools\general.py", line 108, in run
    return Processing.runAlgorithm(algOrName, parameters, onFinish, feedback, context)
  File "C:/PROGRA~1/QGIS3~1.16/apps/qgis/./python/plugins\processing\core\Processing.py", line 153, in runAlgorithm
    raise QgsProcessingException(msg)
_core.QgsProcessingException: Unable to execute algorithm
Incorrect parameter value for CRAYFISH_INPUT_DATASET 
```
F.

**Comment by PeterPetrik** [comment]
The processing algorithms were refactored and moved to QGIS core, please check with the latest master and reopen in QGIS repo if necessary.
