### ISSUE TITLE
Crayfish plugin crashes QGIS.  QGIS 3.22.4-Białowieża

### ISSUE THREAD

**Issue by simonweppe** [lutraconsulting/qgis-crayfish-plugin#499]
Hi there,

I am unable to install the crayfish plugin on QGIS 3.22.

**Comment by simonweppe** [comment]
same happens on a more recent version 3.34

**Comment by simonweppe** [comment]
I finally got to an error message :

```
Couldn't load plugin 'crayfish' due to an error when calling its initGui() method 

AttributeError: module 'pyqtgraph' has no attribute 'GraphicsWindow' 
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 448, in startPlugin
    plugins[packageName].initGui()
  File "/home/simon/.local/share/QGIS/QGIS3/profiles/default/python/plugins/crayfish/plugin.py", line 96, in initGui
    w = CrayfishPlotWidget(self.plot_dock_widget)
  File "/home/simon/.local/share/QGIS/QGIS3/profiles/default/python/plugins/crayfish/gui/plot_widget.py", line 186, in __init__
    self.gw = pyqtgraph.GraphicsWindow()
AttributeError: module 'pyqtgraph' has no attribute 'GraphicsWindow'


Python version: 3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0] 
QGIS version: 3.34.0-Prizren Prizren, ffbdd678812 

Python Path:
/home/simon/.local/share/QGIS/QGIS3/profiles/default/python/plugins/basemesh/packages/markdown2-2.3.8-py2.py3-none-any.whl
/home/simon/.local/share/QGIS/QGIS3/profiles/default/python/plugins/basemesh/packages/py2dm-0.2.1-py3-none-any.whl
/usr/share/qgis/python
/home/simon/.local/share/QGIS/QGIS3/profiles/default/python
/home/simon/.local/share/QGIS/QGIS3/profiles/default/python/plugins
/usr/share/qgis/python/plugins
/usr/lib/python310.zip
/usr/lib/python3.10
/usr/lib/python3.10/lib-dynload
/home/simon/.local/lib/python3.10/site-packages
/usr/local/lib/python3.10/dist-packages
/usr/lib/python3/dist-packages
/home/simon/.local/share/QGIS/QGIS3/profiles/default/python
/home/simon/.local/share/QGIS/QGIS3/profiles/default/python/plugins/basemesh/algorithms
```

**Comment by kermarrecg** [comment]
anyway to overcome that problem? If I reinstall, it geth te same error message

**Comment by HeatherHillers** [comment]
I am seeing this with a fresh OSGeo4W Network Installer install of the qgis-ltr Prizren:

This version comes with pyqtgraph version 0.13.6

QGIS version
3.34.6-Prizren
QGIS code revision
623828f5
Qt version
5.15.13
Python version
3.12.3
GDAL/OGR version
3.8.5
PROJ version
9.4.0
EPSG Registry database version
v11.004 (2024-02-24)
GEOS version
3.12.1-CAPI-1.18.1
SQLite version
3.45.1
PDAL version
2.6.3
PostgreSQL client version
16.2
SpatiaLite version
5.1.0
QWT version
6.2.0
QScintilla2 version
2.14.1
OS version
Windows 10 Version 2009




Active Python plugins
db_manager
0.1.20
ev_cat
3.0
processing
2.12.99
AnotherDXF2Shape
1.3.1
